/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Personas
 * Id: f30c7f72-e9ab-8832-2a57-62944a038809
 * Codename: personas
 */
export type Personas =
  | 'coffee_expert'
  | 'barista'
  | 'cafe_owner'
  | 'coffee_enthusiast'
  | 'coffee_lover'
  | 'coffee_blogger';
