/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Processing
 * Id: d351400e-0290-87b2-1413-6c411d8ae5a4
 * Codename: processing
 */
export type Processing = 'wet__washed_' | 'dry__natural_' | 'semi_dry';
