/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 159e78b3-53be-00bf-4a39-4f5211f2ace4
 */
export const assetFolders = {
  /**
   * Café locations
   */
  caféLocations: {
    id: '958001d8-2228-4373-b966-5262b5b96f71',
    name: 'Café locations',
    externalId: undefined,
    folders: {},
  },
};
