/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 159e78b3-53be-00bf-4a39-4f5211f2ace4
 */
export const taxonomies = {
  /**
   * Processing
   */
  processing: {
    codename: 'processing',
    id: 'd351400e-0290-87b2-1413-6c411d8ae5a4',
    externalId: undefined,
    name: 'Processing',
    terms: {
      wet__washed_: {
        codename: 'wet__washed_',
        id: 'a831d60b-ff0e-7df1-61d2-73e851a5deab',
        externalId: undefined,
        name: 'Wet (Washed)',
        terms: {},
      },
      dry__natural_: {
        codename: 'dry__natural_',
        id: 'ac34eaa7-8463-62b9-825e-66aff9e6b216',
        externalId: undefined,
        name: 'Dry (Natural)',
        terms: {},
      },
      semi_dry: {
        codename: 'semi_dry',
        id: '908321fa-776d-d441-6a72-76fba3959c1d',
        externalId: undefined,
        name: 'Semi-dry',
        terms: {},
      },
    },
  },

  /**
   * Product status
   */
  product_status: {
    codename: 'product_status',
    id: '79b1c5b6-30bc-d076-a236-d9ec9f1ff01b',
    externalId: undefined,
    name: 'Product status',
    terms: {
      on_sale: {
        codename: 'on_sale',
        id: '6352c8bf-8024-9986-8373-35445e1f0d59',
        externalId: undefined,
        name: 'On sale',
        terms: {},
      },
      bestseller: {
        codename: 'bestseller',
        id: '8d808da3-29de-e608-5699-8565687dd474',
        externalId: undefined,
        name: 'Bestseller',
        terms: {},
      },
    },
  },

  /**
   * Sitemap
   */
  sitemap_538125f: {
    codename: 'sitemap_538125f',
    id: '538125ff-c59c-4193-88ce-71a7016830ed',
    externalId: undefined,
    name: 'Sitemap',
    terms: {
      home: {
        codename: 'home',
        id: '796ad1bc-7d9f-426f-97ba-d16003c3f04c',
        externalId: undefined,
        name: 'Home',
        terms: {},
      },
      products: {
        codename: 'products',
        id: '6bb115ce-4f92-44c6-8643-d148f9f7028a',
        externalId: undefined,
        name: 'Products',
        terms: {
          coffee: {
            codename: 'coffee',
            id: '30453aab-633b-4e7c-b9b3-cda95163ad0f',
            externalId: undefined,
            name: 'Coffee',
            terms: {},
          },
          brewers: {
            codename: 'brewers',
            id: 'c66be017-bacc-403f-9f98-8ead623d687e',
            externalId: undefined,
            name: 'Brewers',
            terms: {},
          },
          accessories: {
            codename: 'accessories',
            id: 'baa49a0a-479a-4279-9fe0-f29393f330c5',
            externalId: undefined,
            name: 'Accessories',
            terms: {},
          },
          grinders: {
            codename: 'grinders',
            id: '82b3f64d-a41f-4f78-a410-c6c0e095b3c7',
            externalId: undefined,
            name: 'Grinders',
            terms: {},
          },
        },
      },
      cafes: {
        codename: 'cafes',
        id: '2ab0aad5-7609-4371-8d6e-cb4a917b2ad1',
        externalId: undefined,
        name: 'Cafes',
        terms: {
          north_america: {
            codename: 'north_america',
            id: 'f319b28e-c194-496a-b188-4f91cc010a67',
            externalId: undefined,
            name: 'North America',
            terms: {},
          },
          europe: {
            codename: 'europe',
            id: 'bbac5542-33b5-40ad-a3a9-2f2d37a40ab3',
            externalId: undefined,
            name: 'Europe',
            terms: {},
          },
          australia: {
            codename: 'australia',
            id: '405c6578-8233-4277-9826-6b5e74dc6f39',
            externalId: undefined,
            name: 'Australia',
            terms: {},
          },
        },
      },
      articles: {
        codename: 'articles',
        id: '7ca9b56c-6379-46dc-ae90-3df4b9abd217',
        externalId: undefined,
        name: 'Articles',
        terms: {},
      },
      offices: {
        codename: 'offices',
        id: '3f7bee52-08cc-4a12-8fe9-dbce05871ca0',
        externalId: undefined,
        name: 'Offices',
        terms: {},
      },
      about_us: {
        codename: 'about_us',
        id: 'bbe0ed98-bc68-4f9b-85cb-73cb28078b3c',
        externalId: undefined,
        name: 'About us',
        terms: {},
      },
    },
  },

  /**
   * Personas
   */
  personas: {
    codename: 'personas',
    id: 'f30c7f72-e9ab-8832-2a57-62944a038809',
    externalId: undefined,
    name: 'Personas',
    terms: {
      coffee_expert: {
        codename: 'coffee_expert',
        id: '6693ca6e-79e0-57e4-000d-d23d5ce8f656',
        externalId: undefined,
        name: 'Coffee expert',
        terms: {
          barista: {
            codename: 'barista',
            id: '6a372f43-ccd7-e524-6308-c2094e7b6596',
            externalId: undefined,
            name: 'Barista',
            terms: {},
          },
          cafe_owner: {
            codename: 'cafe_owner',
            id: 'cdf2f3c6-89e3-5df1-f7de-7179460bd6b4',
            externalId: undefined,
            name: 'Cafe owner',
            terms: {},
          },
        },
      },
      coffee_enthusiast: {
        codename: 'coffee_enthusiast',
        id: 'ab2b73a3-473d-4232-0652-495598f5d670',
        externalId: undefined,
        name: 'Coffee enthusiast',
        terms: {
          coffee_lover: {
            codename: 'coffee_lover',
            id: '208a9095-1b92-10da-7627-75ae311935cf',
            externalId: undefined,
            name: 'Coffee lover',
            terms: {},
          },
          coffee_blogger: {
            codename: 'coffee_blogger',
            id: '4fa27320-c363-3ebe-5ab5-b531300f053f',
            externalId: undefined,
            name: 'Coffee blogger',
            terms: {},
          },
        },
      },
    },
  },

  /**
   * Manufacturer
   */
  manufacturer: {
    codename: 'manufacturer',
    id: '4ce421e9-c403-eee8-fdc2-74f09392a749',
    externalId: undefined,
    name: 'Manufacturer',
    terms: {
      aerobie: {
        codename: 'aerobie',
        id: 'f04c8552-1b97-a49b-3944-79275622f471',
        externalId: undefined,
        name: 'Aerobie',
        terms: {},
      },
      chemex: {
        codename: 'chemex',
        id: '16d27bf1-e0f4-8646-0e54-1b71efc6947f',
        externalId: undefined,
        name: 'Chemex',
        terms: {},
      },
      espro: {
        codename: 'espro',
        id: 'b378225f-6dfc-e261-3848-dd030a6d7883',
        externalId: undefined,
        name: 'Espro',
        terms: {},
      },
      hario: {
        codename: 'hario',
        id: '6fde9724-5b72-8bc9-6da0-4f0573a54532',
        externalId: undefined,
        name: 'Hario',
        terms: {},
      },
    },
  },
};
