/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 159e78b3-53be-00bf-4a39-4f5211f2ace4
 */
export const webhooks = {};
