import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 07 Apr 2022 08:01:06 GMT'
 */
export type Accessory = IContentItem<{
  metadataOgDescription: Elements.TextElement;
  metadataMetaTitle: Elements.TextElement;
  metadataOgTitle: Elements.TextElement;
  longDescription: Elements.RichTextElement;
  metadataMetaDescription: Elements.TextElement;
  metadataTwitterSite: Elements.TextElement;
  price: Elements.NumberElement;
  metadataTwitterImage: Elements.AssetsElement;
  metadataTwitterCreator: Elements.TextElement;
  urlPattern: Elements.UrlSlugElement;
  shortDescription: Elements.RichTextElement;
  manufacturer: Elements.TextElement;
  metadataTwitterTitle: Elements.TextElement;
  metadataTwitterDescription: Elements.TextElement;
  metadataOgImage: Elements.AssetsElement;
  sitemap: Elements.TaxonomyElement;
  productStatus: Elements.TaxonomyElement;
  image: Elements.AssetsElement;
  productName: Elements.TextElement;
}>;
