import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 07 Apr 2022 08:01:06 GMT'
 */

export type Article = IContentItem<{
  metadataOgDescription: Elements.TextElement;
  metadataMetaTitle: Elements.TextElement;
  personas: Elements.TaxonomyElement;
  bodyCopy: Elements.RichTextElement;
  metadataOgTitle: Elements.TextElement;
  metadataMetaDescription: Elements.TextElement;
  metadataTwitterSite: Elements.TextElement;
  postDate: Elements.DateTimeElement;
  metaKeywords: Elements.TextElement;
  teaserImage: Elements.AssetsElement;
  metadataTwitterImage: Elements.AssetsElement;
  metadataTwitterCreator: Elements.TextElement;
  title: Elements.TextElement;
  summary: Elements.TextElement;
  sitemap: Elements.TaxonomyElement;
  metadataTwitterTitle: Elements.TextElement;
  metadataTwitterDescription: Elements.TextElement;
  metaDescription: Elements.TextElement;
  metadataOgImage: Elements.AssetsElement;
  relatedArticles: Elements.LinkedItemsElement<Article>;
  urlPattern: Elements.UrlSlugElement;
}>;
