import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 07 Apr 2022 08:01:06 GMT'
 */
export type HeroUnit = IContentItem<{
  sitemap: Elements.TaxonomyElement;
  title: Elements.TextElement;
  image: Elements.AssetsElement;
  marketingMessage: Elements.RichTextElement;
}>;
