import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 07 Apr 2022 08:01:06 GMT'
 */
export type Home = IContentItem<{
  metadataOgDescription: Elements.TextElement;
  metadataMetaTitle: Elements.TextElement;
  metadataOgTitle: Elements.TextElement;
  articles: Elements.LinkedItemsElement<IContentItem>;
  heroUnit: Elements.LinkedItemsElement<IContentItem>;
  metadataMetaDescription: Elements.TextElement;
  metadataTwitterSite: Elements.TextElement;
  ourStory: Elements.LinkedItemsElement<IContentItem>;
  cafes: Elements.LinkedItemsElement<IContentItem>;
  metadataTwitterImage: Elements.AssetsElement;
  metadataTwitterCreator: Elements.TextElement;
  metadataTwitterTitle: Elements.TextElement;
  metadataTwitterDescription: Elements.TextElement;
  metadataOgImage: Elements.AssetsElement;
  urlPattern: Elements.UrlSlugElement;
  sitemap: Elements.TaxonomyElement;
  contact: Elements.RichTextElement;
}>;
