import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Sitemap } from '../taxonomies/sitemap_538125f';

/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Cafe
 * Id: fe41ae5a-5fe2-420a-8560-f7d6d3533dc2
 * Codename: cafe
 */
export type Cafe = IContentItem<{
  /**
   * Street (text)
   * Required: false
   * Id: 866afdba-d334-f01a-1d52-a9ca3f57cb4b
   * Codename: street
   */
  street: Elements.TextElement;

  /**
   * City (text)
   * Required: false
   * Id: 339e6d4f-67c1-5f5e-6921-3b374eb96f5b
   * Codename: city
   */
  city: Elements.TextElement;

  /**
   * Country (text)
   * Required: false
   * Id: 7531a08f-e148-8cc0-9d2d-155215502e08
   * Codename: country
   */
  country: Elements.TextElement;

  /**
   * State (text)
   * Required: false
   * Id: a015b689-cad3-1ac9-04b4-73697525752d
   * Codename: state
   */
  state: Elements.TextElement;

  /**
   * ZIP Code (text)
   * Required: false
   * Id: bb158ac2-41e1-5a7d-0826-bb8bf6744f0e
   * Codename: zip_code
   */
  zipCode: Elements.TextElement;

  /**
   * Phone (text)
   * Required: false
   * Id: 1c71bc62-4b62-f307-37ef-0823776f8f73
   * Codename: phone
   */
  phone: Elements.TextElement;

  /**
   * Email (text)
   * Required: false
   * Id: 6f726c77-36bd-8062-51df-056136e10d35
   * Codename: email
   */
  email: Elements.TextElement;

  /**
   * Photo (asset)
   * Required: false
   * Id: 5769c0f4-66a8-4c73-3c19-c023bdfa123a
   * Codename: photo
   */
  photo: Elements.AssetsElement;

  /**
   * Sitemap (taxonomy)
   * Required: false
   * Id: e82d0f49-5b15-45e1-9b1f-32ccc1be4941
   * Codename: sitemap
   */
  sitemap: Elements.TaxonomyElement<Sitemap>;
}>;
