import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ProductStatus } from '../taxonomies/product_status';
import { Processing } from '../taxonomies/processing';
import { Sitemap } from '../taxonomies/sitemap_538125f';

/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Coffee
 * Id: 929985ac-4aa5-436b-85a2-94c2d4fbbebd
 * Codename: coffee
 */
export type Coffee = IContentItem<{
  /**
   * Product name (text)
   * Required: false
   * Id: edaec5c4-e653-9109-eb0d-fc40ccf3c810
   * Codename: product_name
   *
   * Include a product display name.
   */
  productName: Elements.TextElement;

  /**
   * Price (number)
   * Required: false
   * Id: 624592dc-49b2-330a-7185-e1f2396ce90c
   * Codename: price
   *
   * Include a product price.
   */
  price: Elements.NumberElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 30ac3ccc-1e7f-1490-e1f6-915c64176a55
   * Codename: image
   *
   * Upload a product image; the recommended size is 300 × 300 px.
   */
  image: Elements.AssetsElement;

  /**
   * Short description (rich_text)
   * Required: false
   * Id: b5a3263a-a1d7-92b7-865a-329f833285fa
   * Codename: short_description
   *
   * Include a short description that fits within 160 characters.
   */
  shortDescription: Elements.RichTextElement;

  /**
   * Long description (rich_text)
   * Required: false
   * Id: d468a0aa-e0fa-0cae-41db-6e006bff2527
   * Codename: long_description
   *
   * Include a full product description.
   */
  longDescription: Elements.RichTextElement;

  /**
   * Product status (taxonomy)
   * Required: false
   * Id: 1ee64175-fde7-fc1e-5259-511a31c326c3
   * Codename: product_status
   *
   * Add a product status if the product is included in a special offering.
   */
  productStatus: Elements.TaxonomyElement<ProductStatus>;

  /**
   * Farm (text)
   * Required: false
   * Id: e5cf103f-9b84-1ab0-29f1-fb5a1657c6f7
   * Codename: farm
   *
   * Include the name of the coffee farm.
   */
  farm: Elements.TextElement;

  /**
   * Country (text)
   * Required: false
   * Id: 6eec1918-378d-3b15-8b1a-19c5f0748321
   * Codename: country
   *
   * Include  the coffee's country of origin.
   */
  country: Elements.TextElement;

  /**
   * Variety (text)
   * Required: false
   * Id: 301c6712-962f-b05a-6f6e-2f0e1e959039
   * Codename: variety
   *
   * Include a coffee variety name.
   */
  variety: Elements.TextElement;

  /**
   * Altitude (text)
   * Required: false
   * Id: 23a772c0-0b2b-588d-9849-e29068701f03
   * Codename: altitude
   *
   * Include the altitude at which the coffee is grown. Elevation affects the size, shape, and taste of coffee beans.
   */
  altitude: Elements.TextElement;

  /**
   * URL pattern (url_slug)
   * Required: false
   * Id: 3af8ce38-c03d-063c-ea80-72684dfddf31
   * Codename: url_pattern
   *
   * Provide a SEO-friendly URL.
   */
  urlPattern: Elements.UrlSlugElement;

  /**
   * Processing (taxonomy)
   * Required: false
   * Id: b63e3516-d5fa-fdac-a03a-2b027bf02a28
   * Codename: processing
   */
  processing: Elements.TaxonomyElement<Processing>;

  /**
   * Sitemap (taxonomy)
   * Required: false
   * Id: 99d7a378-e18f-41dd-b5bb-2a569c3d1de7
   * Codename: sitemap
   */
  sitemap: Elements.TaxonomyElement<Sitemap>;

  /**
   * Meta title (text)
   * Required: false
   * Id: 09398b24-61ed-512e-5b5c-affd54a098e5
   * Codename: metadata__meta_title
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Length: 30–60 characters
   */
  metadataMetaTitle: Elements.TextElement;

  /**
   * Meta description (text)
   * Required: false
   * Id: 2e555cc1-1eae-520c-189e-28548904f529
   * Codename: metadata__meta_description
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Length: 70–150 characters
   */
  metadataMetaDescription: Elements.TextElement;

  /**
   * og:title (text)
   * Required: false
   * Id: 1db86c7a-e836-3c4e-01e6-4f704ad38ba5
   * Codename: metadata__og_title
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Max. 60 characters
   */
  metadataOgTitle: Elements.TextElement;

  /**
   * og:description (text)
   * Required: false
   * Id: 05987dc9-ebe3-7b61-b949-522eb42dbc0d
   * Codename: metadata__og_description
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Max. 150 characters
   */
  metadataOgDescription: Elements.TextElement;

  /**
   * og:image (asset)
   * Required: false
   * Id: ce6cda71-9d38-1d57-3ac3-ec9b2e286edd
   * Codename: metadata__og_image
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Use images that are at least 1200 × 630 px for best display on high resolution devices. At the minimum, you should use images that are 600 × 315 px to display link page posts with larger images. Images may be up to 1 MB in size.
   */
  metadataOgImage: Elements.AssetsElement;

  /**
   * twitter:site (text)
   * Required: false
   * Id: 34213fdf-0015-8f4f-e5e6-83c6842cff4a
   * Codename: metadata__twitter_site
   * From snippet: Metadata
   * Snippet codename: metadata
   */
  metadataTwitterSite: Elements.TextElement;

  /**
   * twitter:creator (text)
   * Required: false
   * Id: 68f65095-c9b4-05d6-a473-2883c2f0c7af
   * Codename: metadata__twitter_creator
   * From snippet: Metadata
   * Snippet codename: metadata
   */
  metadataTwitterCreator: Elements.TextElement;

  /**
   * twitter:title (text)
   * Required: false
   * Id: b208d3dc-bd8d-b1af-5ef0-747650730ba7
   * Codename: metadata__twitter_title
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Max. 60 characters
   */
  metadataTwitterTitle: Elements.TextElement;

  /**
   * twitter:description (text)
   * Required: false
   * Id: b7d1dd8b-a5d8-2ad8-2f57-49881363f6f7
   * Codename: metadata__twitter_description
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * A description that concisely summarizes the content as appropriate for presentation within a Tweet. You should not re-use the title as the description, or use this field to describe the general services provided by the website. Max. 150 characters.
   */
  metadataTwitterDescription: Elements.TextElement;

  /**
   * twitter:image (asset)
   * Required: false
   * Id: 63793ba4-6004-a93c-68ca-52a1f0482bca
   * Codename: metadata__twitter_image
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Twitter's recommendation: A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card should be at least 280 × 150 px. Images may be up to 1 MB in size.Let's go for 560 × 300 px.
   */
  metadataTwitterImage: Elements.AssetsElement;
}>;
