import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Sitemap } from '../taxonomies/sitemap_538125f';
import { Article } from './article';
import { Cafe } from './cafe';
import { FactAboutUs } from './fact_about_us';
import { HeroUnit } from './hero_unit';

/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Home
 * Id: a29399c3-5281-47ab-9916-acd4a6f887b7
 * Codename: home
 */
export type Home = IContentItem<{
  /**
   * Hero unit (modular_content)
   * Required: false
   * Id: 2b15a8f3-2e5f-7d01-4d8e-5b22e222aa76
   * Codename: hero_unit
   *
   * Assign 1 Hero unit that has been prepared for a home page.
   */
  heroUnit: Elements.LinkedItemsElement<HeroUnit>;

  /**
   * Articles (modular_content)
   * Required: false
   * Id: 222f3a69-a54f-3e92-83ac-05f8a08e667f
   * Codename: articles
   *
   * Assign all articles which should be displayed on the home page.
   */
  articles: Elements.LinkedItemsElement<Article>;

  /**
   * Our story (modular_content)
   * Required: false
   * Id: 617bccc0-4844-4beb-4ede-6247e954633a
   * Codename: our_story
   *
   * Assign 1 Fact about us which will be displayed on the home page.
   */
  ourStory: Elements.LinkedItemsElement<FactAboutUs>;

  /**
   * Cafes (modular_content)
   * Required: false
   * Id: 6356c948-0fd6-00d0-8fc1-e2484180ae7c
   * Codename: cafes
   *
   * Assign 4 Cafes which will be displayed on the home page.
   */
  cafes: Elements.LinkedItemsElement<Cafe>;

  /**
   * Contact (rich_text)
   * Required: false
   * Id: ee854076-236b-5312-0ed5-8c3cd55ca9e0
   * Codename: contact
   *
   * Add Contact us information to be displayed on the home page.
   */
  contact: Elements.RichTextElement;

  /**
   * URL pattern (url_slug)
   * Required: false
   * Id: dd70db4b-ee97-5ab4-b752-4f9d70389426
   * Codename: url_pattern
   *
   * Provide a SEO-friendly URL.
   */
  urlPattern: Elements.UrlSlugElement;

  /**
   * Sitemap (taxonomy)
   * Required: false
   * Id: ea3bf3c2-7eb7-4c91-aff3-09f89c743710
   * Codename: sitemap
   */
  sitemap: Elements.TaxonomyElement<Sitemap>;

  /**
   * Meta title (text)
   * Required: false
   * Id: 09398b24-61ed-512e-5b5c-affd54a098e5
   * Codename: metadata__meta_title
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Length: 30–60 characters
   */
  metadataMetaTitle: Elements.TextElement;

  /**
   * Meta description (text)
   * Required: false
   * Id: 2e555cc1-1eae-520c-189e-28548904f529
   * Codename: metadata__meta_description
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Length: 70–150 characters
   */
  metadataMetaDescription: Elements.TextElement;

  /**
   * og:title (text)
   * Required: false
   * Id: 1db86c7a-e836-3c4e-01e6-4f704ad38ba5
   * Codename: metadata__og_title
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Max. 60 characters
   */
  metadataOgTitle: Elements.TextElement;

  /**
   * og:description (text)
   * Required: false
   * Id: 05987dc9-ebe3-7b61-b949-522eb42dbc0d
   * Codename: metadata__og_description
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Max. 150 characters
   */
  metadataOgDescription: Elements.TextElement;

  /**
   * og:image (asset)
   * Required: false
   * Id: ce6cda71-9d38-1d57-3ac3-ec9b2e286edd
   * Codename: metadata__og_image
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Use images that are at least 1200 × 630 px for best display on high resolution devices. At the minimum, you should use images that are 600 × 315 px to display link page posts with larger images. Images may be up to 1 MB in size.
   */
  metadataOgImage: Elements.AssetsElement;

  /**
   * twitter:site (text)
   * Required: false
   * Id: 34213fdf-0015-8f4f-e5e6-83c6842cff4a
   * Codename: metadata__twitter_site
   * From snippet: Metadata
   * Snippet codename: metadata
   */
  metadataTwitterSite: Elements.TextElement;

  /**
   * twitter:creator (text)
   * Required: false
   * Id: 68f65095-c9b4-05d6-a473-2883c2f0c7af
   * Codename: metadata__twitter_creator
   * From snippet: Metadata
   * Snippet codename: metadata
   */
  metadataTwitterCreator: Elements.TextElement;

  /**
   * twitter:title (text)
   * Required: false
   * Id: b208d3dc-bd8d-b1af-5ef0-747650730ba7
   * Codename: metadata__twitter_title
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Max. 60 characters
   */
  metadataTwitterTitle: Elements.TextElement;

  /**
   * twitter:description (text)
   * Required: false
   * Id: b7d1dd8b-a5d8-2ad8-2f57-49881363f6f7
   * Codename: metadata__twitter_description
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * A description that concisely summarizes the content as appropriate for presentation within a Tweet. You should not re-use the title as the description, or use this field to describe the general services provided by the website. Max. 150 characters.
   */
  metadataTwitterDescription: Elements.TextElement;

  /**
   * twitter:image (asset)
   * Required: false
   * Id: 63793ba4-6004-a93c-68ca-52a1f0482bca
   * Codename: metadata__twitter_image
   * From snippet: Metadata
   * Snippet codename: metadata
   *
   * Twitter's recommendation: A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card should be at least 280 × 150 px. Images may be up to 1 MB in size.Let's go for 560 × 300 px.
   */
  metadataTwitterImage: Elements.AssetsElement;
}>;
